# Generated by Django 5.0.1 on 2024-09-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='likecount',
        ),
        migrations.AddField(
            model_name='comments',
            name='likecount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
