# Generated by Django 5.0.1 on 2024-09-28 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_remove_blogpost_likecount_comments_likecount'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='type',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='pimage',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
