# Generated by Django 5.0.1 on 2024-12-27 09:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_blogpost_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogpost',
            new_name='Recipepost',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='blogpost',
            new_name='Recipepost',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('Recipepost', 'user')},
        ),
    ]
